### PR TITLE
Restructure Repo

### PR DESCRIPTION
**Pull request by j-rossi-nl**
solves #1 

* FIRST COMMIT: no tests / no pre-commit

* using cookiecutter + hypermodern python
* setting up poetry as dependency manager / package builder / package uploader
* pre-commit hooks
* github actions

### CODE REVIEW

**Comment by j-rossi-nl** [comment]
To be done:
* tests should be OK
* pre-commit should run (flake8 should be happy)
* mypy / safety should be happy
* limit the number of running actions
* configure repo with PYPI and PYPI_TEST tokens as secrets (for automatic upload)
* configure read-the-docs / codecov to track project

**Comment by j-rossi-nl** [comment]
pytest is running fine now, yay !! :+1: 

Still to do:

- [ ] flake8 errors
- [ ] commit with pre-commit activated
- [ ] mypy (not a single type hinting at the moment)

**Comment by Ziip-dev** [comment]
I am trying to understand your process so far. Do you, by any chance, have a good resource in mind from which I can learn the basics of github actions, project structure, required automation and verification usually implemented in serious projects?
Actually this is the part I have less knowledge about...

**Comment by j-rossi-nl** [comment]
I'm taking most of things from [Hypermodern Python](https://medium.com/@cjolowicz/hypermodern-python-d44485d9d769).
Basically, on top of "just the source code" of the package, you consider having programs that check:
* code is properly written (black, isort)
* code does not contain potential bugs (flake8)
* code uses only "safe" packages and has no known security vulnerability (safety)
* code is entirely type-hinted (mypy)
* code is properly documented (flake8)
* code is tested (pytest, coverage)

Pre-Commit: only accept a commit when some checks are OK. The checks run on the developer computer when you run a git commit command

Github Actions: only merge a PR when checks are OK. Actions run in virtual machines provided by Github. This includes more checks than the pre-commit (mypy, pytest, ...)

**Comment by j-rossi-nl** [comment]
Get all of this without errors (see Github Actions)

- [ ] pre-commit (ie flake8)
- [X] mypy 
- [X] tests
- [ ] typeguard
- [X] xdoctest
- [X] docs-build

**Comment by chemelli74** [comment]
Great job @j-rossi-nl !

While at it, I think the repo itself need a rename.

Simone

**Comment by Ziip-dev** [comment]
> I'm taking most of things from [Hypermodern Python](https://medium.com/@cjolowicz/hypermodern-python-d44485d9d769).
Basically, on top of "just the source code" of the package, you consider having programs that check:
* code is properly written (black, isort)
* code does not contain potential bugs (flake8)
* code uses only "safe" packages and has no known security vulnerability (safety)
* code is entirely type-hinted (mypy)
* code is properly documented (flake8)
* code is tested (pytest, coverage)

Pre-Commit: only accept a commit when some checks are OK. The checks run on the developer computer when you run a git commit command

Github Actions: only merge a PR when checks are OK. Actions run in virtual machines provided by Github. This includes more checks than the pre-commit (mypy, pytest, ...)

 

Guess I'll truly have to dig into this hypermodern series, I read some parts of it in the past but I still need practice

**Comment by j-rossi-nl** [comment]
closes #1

**Pull request merged**
